### ISSUE TITLE
Classification profile crashed when run the 2nd instance switch from CPU to GPU.0

### ISSUE THREAD

**Issue by jim-wang-intel** [intel-retail/automated-self-checkout#322]
## Version

What release version was the issue found in? main branch

## Hardware configuration
NUC with integrated GPU

List Hardware components used. 
Ex. 
Issue found with the following:
- Intel® xeon Platinum 8351N with Intel® Data Center GPU Flex 140
- 12th Gen Intel® Core™ i7 with Intel® Arc™ A770M Graphics

## Describe the bug
When launched the 2nd instance of classification profile instance of run.sh switched from device CPU to GPU.0 (or GPU), the python-web application crashed and thus causing the cid_count messed up so that no more instance can be launched any more.
In the r0.jsonl file it shows the error for the crashed app log:
```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 47, in predict
    raw_response = self.prediction_service_stub.Predict(request.raw_request, timeout)
  File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.10/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Model with requested version is not found"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:9000 {created_time:"2023-10-24T23:59:29.175770228+00:00", grpc_status:5, grpc_message:"Model with requested version is not found"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/classification/python/classification_demo.py", line 345, in <module>
    sys.exit(main() or 0)
  File "/app/classification/python/classification_demo.py", line 293, in main
    async_pipeline.submit_data(frame, next_frame_id, {'frame': frame, 'start_time': start_time})
  File "/app/common/python/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 110, in submit_data
    self.model.infer_async(inputs, callback_data)
  File "/app/common/python/openvino/model_zoo/model_api/models/model.py", line 284, in infer_async
    self.model_adapter.infer_async(dict_data, callback_data)
  File "/app/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py", line 152, in infer_async
    raw_result = self.client.predict(inputs, model_name=self.model_name, model_version=self.model_version)
  File "/usr/local/lib/python3.10/site-packages/ovmsclient/tfs_compat/grpc/serving_client.py", line 49, in predict
    raise_from_grpc(grpc_error)
  File "/usr/local/lib/python3.10/site-packages/ovmsclient/tfs_compat/base/errors.py", line 66, in raise_from_grpc
    raise (error_class(details))
ovmsclient.tfs_compat.base.errors.ModelNotFoundError: Error occurred during handling the request: Model with requested version is not found
```

On the later instance, trying to launch, then the profile-launcher log shows:
```console
2023/10/24 17:12:58 found error while launching pipeline script: found error while executing pipeline scripts- stdErrMsg: docker: Error response from daemon: Conflict. The container name "/classification1" is already in use by container "4cdf2735b62ffc5e78bee03f17351ae8477a27fdbca5a22f2ab2574665afb39f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
, Err: exit status 125
```
It is due to the first instance crashed and exited out so that the cid_count is only 1 running.

## To Reproduce

1. make clean-all
2. make run-camera-simulator
3. run classification profile: `PIPELINE_PROFILE="classification" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms`
4. docker ps -a and it shows runs ok for the 1st instance of python app docker container named classification0
5. now, switch to run on GPU.0 for the same classification profile: `DEVICE="GPU.0" PIPELINE_PROFILE="classification" RENDER_MODE=1 sudo -E ./run.sh --platform dgpu.0 --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms`
6. docker ps -a now it shows the classification0 python web container crashed:
```console
$ docker ps -a
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                      PORTS     NAMES
4cdf2735b62f   python-demo:dev                           "bash -c $DOCKER_CMD"    19 minutes ago   Up 19 minutes                         classification1
8e7acf0bb845   openvino/model_server:2023.1-gpu          "/ovms/bin/ovms --co…"   19 minutes ago   Up 19 minutes                         ovms-server1
7d09a73d3550   python-demo:dev                           "bash -c $DOCKER_CMD"    20 minutes ago   Exited (0) 19 minutes ago             classification0
84812a2e7e8f   openvino/model_server:2023.1-gpu          "/ovms/bin/ovms --co…"   20 minutes ago   Up 20 minutes                         ovms-server0
dd04b525c74c   openvino/ubuntu20_data_runtime:2021.4.2   "ffmpeg -nostdin -re…"   20 minutes ago   Up 20 minutes                         camera-simulator2
14e7f51c2c95   openvino/ubuntu20_data_runtime:2021.4.2   "ffmpeg -nostdin -re…"   20 minutes ago   Up 20 minutes                         camera-simulator1
e63ceaa70552   openvino/ubuntu20_data_runtime:2021.4.2   "ffmpeg -nostdin -re…"   20 minutes ago   Up 20 minutes                         camera-simulator0
28907f536d67   aler9/rtsp-simple-server                  "/mediamtx"              20 minutes ago   Up 20 minutes                         camera-simulator
```
the log of profile launcher shows that 
```console
2023/10/24 17:12:58 found error while launching pipeline script: found error while executing pipeline scripts- stdErrMsg: docker: Error response from daemon: Conflict. The container name "/classification1" is already in use by container "4cdf2735b62ffc5e78bee03f17351ae8477a27fdbca5a22f2ab2574665afb39f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
, Err: exit status 125
```

which means that the count of cid_count is messed up and hence the later instance of classification Docker container cannot launch successfully until clean all instances up.

Notice that if we launch the first instance as GPU.0 then it seems work without crashed.

## Dependency and notes
Related to issue #328, though the #328 cannot totally solve the issue of python app crashed itself.

**Comment by vli11** [comment]
I dont' see the same error

**Comment by jim-wang-intel** [comment]
the #328 resolves the issue of subsequent profile-launcher wouldn't be able to launch more pipelines; however, **the OVMS server unstable issue after switching from CPU to GPU.0** still exists, and the instance of the first ovms server cannot be in stable state for some reason and i think it is OVMS server bug.    

The Docker logs of the first ovms server:
```console
$  docker logs ovms-server0

[2023-11-03 17:27:36.799][78][serving][info][model.cpp:252] Will reload model: bit_64; version: 1 ...
[2023-11-03 17:27:36.799][78][serving][info][model.cpp:41] Getting model from /models/BiT_M_R50x1_10C_50e_IR/FP16-INT8
[2023-11-03 17:27:36.799][78][serving][info][model.cpp:48] Model downloaded to /models/BiT_M_R50x1_10C_50e_IR/FP16-INT8
[2023-11-03 17:27:36.799][78][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model bit_64 status change. New status: ( "state": "LOADING", "error_code": "OK" )
[2023-11-03 17:27:36.843][78][modelmanager][info][modelinstance.cpp:453] Input name: input_1; mapping_name: input_1; shape: (1,64,64,3); precision: FP32; layout: NHWC
[2023-11-03 17:27:36.843][78][modelmanager][info][modelinstance.cpp:501] Output name: output_1; mapping_name: output_1; shape: (1,2048); precision: FP32; layout: N...
[2023-11-03 17:27:36.843][78][modelmanager][error][modelinstance.cpp:694] Cannot compile model into target device; error: Exception from src/inference/src/core.cpp:114:
[ GENERAL_ERROR ] Check '!device_map.empty()' failed at src/plugins/intel_gpu/src/plugin/plugin.cpp:550:
[GPU] Can't get DEVICE_ID property as no supported devices found or an error happened during devices query.
[GPU] Please check OpenVINO documentation for GPU drivers setup guide.


; model: bit_64; version: 1; device: GPU.0
[2023-11-03 17:27:36.843][78][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model bit_64 status change. New status: ( "state": "LOADING", "error_code": "UNKNOWN" )
[2023-11-03 17:27:36.843][78][serving][error][model.cpp:276] Error occurred while loading model: bit_64; version: 1; error: Cannot compile model into target device
[2023-11-03 17:27:36.843][78][modelmanager][error][modelmanager.cpp:1381] Error occurred while reloading model: bit_64; versions; error: Cannot compile model into target device
[2023-11-03 17:27:36.843][78][serving][info][model.cpp:190] Will clean up model: bit_64; version: 1 ...
[2023-11-03 17:27:36.843][78][serving][info][model.cpp:88] Updating default version for model: bit_64, from: 0
[2023-11-03 17:27:36.843][78][serving][info][model.cpp:100] Model: bit_64 will not have default version since no version is available.
[2023-11-03 17:27:36.843][78][serving][info][modelversionstatus.cpp:109] STATUS CHANGE: Version 1 of model bit_64 status change. New status: ( "state": "LOADING", "error_code": "UNKNOWN" )

```

**Comment by jim-wang-intel** [comment]
The root cause of this is due to sharing of same config.json file among different instances of OVMS servers.  The first instance of OVMS server only have device CPU mounted to that container; while the 2nd instance of OVMS server having the GPU.device mounted in its own container, the config.json was updated to GPU and the first instance doesn't have such device mounted.
